name: build-and-deploy
on:
  push:
    branches: [ nextjs-version ]
    paths-ignore:
      - 'action/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'nextjs-version'
    - name: Build
      run: |
        npm install && npm run build && npm run export
    - name: create nojekyll 
      run: |
        touch docs/_next/.nojekyll
    - name: commit
      run: |
        git config --global user.email actions@github.com
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto depoly by Action" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.action_token }}
        branch: 'master'
        force: true
    # - name: Deploy
    #   run: |
    #     git config user.email "github action"
    #     git config user.name "github action"
    #     git add -A
    #     git commit -m "auto build from action"
    #     remote_repo="https://${GITHUB_ACTOR}:${{ secrets.action_token }}@github.com/${GITHUB_REPOSITORY}.git"
    #     INPUT_BRANCH=${INPUT_BRANCH:-webpack-build}
    #     git push "${remote_repo}" HEAD:${INPUT_BRANCH}

        