name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - webpack-build
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.action_token }}
        BRANCH: webpack-build
        FOLDER: docs
        BUILD_SCRIPT: npm install && npm run build