name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - webpack-build
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        npm install || npm run build
    - name: Deploy
      run: |
        git config user.email "github action"
        git config user.name "github action"
        git branch -a
        